<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2022. HUINNO Co., Ltd. All rights reserved</name>
   <tag></tag>
   <elementGuidId>04d4c6d4-75e6-4610-bbf0-21827b10332e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-lkgTHX.ifsjJA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>913f387d-7c18-478b-9e42-e6ca6b557261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-lkgTHX ifsjJA</value>
      <webElementGuid>4861e94c-31ff-4d07-a92f-b2679f232f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>비밀번호로그인비밀번호를 잊어버리셨나요?© 2022. HUINNO Co., Ltd. All rights reserved.</value>
      <webElementGuid>6f7cae1e-09f1-4ded-8daa-ac6ae8de61a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-eGRUor cOTRZE&quot;]/div[@class=&quot;sc-ctqQKy efYUQn&quot;]/div[@class=&quot;sc-fmBCVi kagCfw&quot;]/div[@class=&quot;sc-lkgTHX ifsjJA&quot;]</value>
      <webElementGuid>aa18e1bd-d311-4bd5-8399-663b9b30da75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div</value>
      <webElementGuid>980750a4-887b-4582-bb5b-8deb3f411ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>96591e89-2958-4973-a915-b7ae92baf130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '비밀번호로그인비밀번호를 잊어버리셨나요?© 2022. HUINNO Co., Ltd. All rights reserved.' or . = '비밀번호로그인비밀번호를 잊어버리셨나요?© 2022. HUINNO Co., Ltd. All rights reserved.')]</value>
      <webElementGuid>16cb1007-b951-4993-b9fb-10096bc2e3bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
