<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pause</name>
   <tag></tag>
   <elementGuidId>805d9c6a-30da-465b-b837-6084f2067fc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-kBzgEd.xTxhm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34c069e1-3634-47ac-b7c5-42443b9827d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-kBzgEd xTxhm</value>
      <webElementGuid>5cd97720-fab8-4ad6-b5e7-dfcc513b65cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pause</value>
      <webElementGuid>cb4ef94c-cd89-4147-997d-f1e4a906b006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-jWUzzU dgZbAM&quot;]/div[@class=&quot;sc-eFegNN cGKrit&quot;]/div[@class=&quot;sc-kMyqmI iPSAWW&quot;]/div[@class=&quot;sc-dUbtfd jfyZaM&quot;]/div[@class=&quot;sc-jwQYvw krqfKW&quot;]/div[@class=&quot;sc-juEPzu bRPFz&quot;]/div[@class=&quot;sc-dMOJrz GvDwq&quot;]/div[@class=&quot;sc-fIITEw jgRMlC&quot;]/div[@class=&quot;sc-cQMzAB eMEvEG&quot;]/div[@class=&quot;sc-ezHhwS gmbBW&quot;]/div[@class=&quot;sc-kBzgEd xTxhm&quot;]</value>
      <webElementGuid>7883266e-c04c-4d5c-bca4-a597ad4ef835</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div</value>
      <webElementGuid>9e8f8d18-a9a0-4641-912a-aedda96fa943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ep(s)'])[1]/following::div[2]</value>
      <webElementGuid>ae2ce378-acb2-4310-8fe6-622c84b50507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AF'])[2]/following::div[5]</value>
      <webElementGuid>4df8b58b-32fe-4ca1-894d-89006d3c769d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ep(s)'])[2]/preceding::div[2]</value>
      <webElementGuid>6d88e3df-3060-4dd0-8e20-23ba657665bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VT'])[1]/preceding::div[4]</value>
      <webElementGuid>3b210e12-4c53-47b8-a359-bad672c97d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div</value>
      <webElementGuid>a2baaa45-cc96-4e5c-8822-1a59ff61d88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pause' or . = 'Pause')]</value>
      <webElementGuid>3ae060db-321f-414c-883d-05fb8c36968b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
