<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_53</name>
   <tag></tag>
   <elementGuidId>cf264270-087b-48b7-a774-2bc6f1776f56</elementGuidId>
   <imagePath>Screenshots/Targets/Object Repository/SQA-63/Page_MEMO Care/div_53.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-eSxRXt.hCshtw > div.sc-aaqME.bZakZQ</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Object Repository/SQA-63/Page_MEMO Care/div_53.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3fd5f041-ef01-4a8e-b832-be96348e7f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-aaqME bZakZQ</value>
      <webElementGuid>22ba73fe-4617-4a8a-b8c5-6b4bb8e23543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>53</value>
      <webElementGuid>6a41c497-69d8-4602-8abb-b4776d64fed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-jWUzzU dgZbAM&quot;]/div[@class=&quot;sc-eFegNN cGKrit&quot;]/div[@class=&quot;sc-eBHJIF jnAICa&quot;]/div[@class=&quot;sc-ewSTlh jlayFw&quot;]/div[@class=&quot;sc-fDMmqs hWPHwC&quot;]/div[@class=&quot;sc-cdJjGe kLdrRj&quot;]/div[@class=&quot;sc-cOLXoO GXKoS&quot;]/div[@class=&quot;sc-kszsFN eIOYoP&quot;]/div[@class=&quot;sc-iLOkMM cKVUQN&quot;]/div[@class=&quot;sc-jefHZX gNJmbq&quot;]/div[@class=&quot;sc-eSxRXt hCshtw&quot;]/div[@class=&quot;sc-aaqME bZakZQ&quot;]</value>
      <webElementGuid>5555158c-6ff4-4788-8805-563534409ebb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div</value>
      <webElementGuid>ea6a669e-0d10-4c60-b5ff-dda0a85af637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pause'])[2]/following::div[2]</value>
      <webElementGuid>30cf9c07-724f-4d55-837b-6fe6e6469514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ep(s)'])[1]/following::div[4]</value>
      <webElementGuid>51621899-caae-4a1d-bf6b-15df57b320d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ep(s)'])[2]/preceding::div[1]</value>
      <webElementGuid>16eb7901-0c22-4539-951f-02701b615b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VT'])[1]/preceding::div[2]</value>
      <webElementGuid>ee9d24d7-bdcd-47cc-b6c2-9c6ff29e6ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='53']/parent::*</value>
      <webElementGuid>1db0d782-1d90-4dff-8842-41515f5ff6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div</value>
      <webElementGuid>2ae1f154-4e4b-489d-991c-752a2a7b6ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '53' or . = '53')]</value>
      <webElementGuid>6ff1767f-8a69-4875-a611-6b2e712337e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
