<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>g_Created with Highcharts 9.3.2_huinno-even_4e2258 (1)</name>
   <tag></tag>
   <elementGuidId>16e27e7b-e9d1-4467-a207-d07a39b9111f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#highcharts-jivpkqq-131097 > svg.highcharts-root > g.huinno-event-marker-group</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>g</value>
      <webElementGuid>911c7a0f-1d26-494b-bc00-ed4ebf98c803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-event-marker-group</value>
      <webElementGuid>a1fc59d0-69dd-49f8-8a55-167be3041779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1ec5ff06-665f-4336-9675-6181e764b107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-jivpkqq-131097&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;huinno-event-marker-group&quot;]</value>
      <webElementGuid>f69207db-e4a4-44b5-9968-71f2ab0e08fc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
