<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_Created with Highcharts 9.3.2_huinno-m_7ff2e6</name>
   <tag></tag>
   <elementGuidId>463f884b-73f6-487e-828a-6d0ca7042b45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#highcharts-i8v60ol-2483624 > svg.highcharts-root > g.huinno-mouse-tracker-g > path.huinno-mouse-tracker</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>d9b9bac0-3b98-4045-9926-7e9d5ef6ec63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7a7582a6-8d2a-4e2b-b545-458266d00a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-mouse-tracker</value>
      <webElementGuid>d3f8599f-fd44-4925-9ad0-be3f4776a554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M0 17 V44</value>
      <webElementGuid>7a1b16c0-f9d6-4037-ad4b-60ff20f7cad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>rgb(66, 106, 255)</value>
      <webElementGuid>3cfc68c7-a8e5-400a-a6dd-ea3e68269d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c7d565d6-991c-4316-a716-1b8eff4d1f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-dasharray</name>
      <type>Main</type>
      <value>2,2</value>
      <webElementGuid>1d80dafe-94d7-484c-89a6-2830caddf79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>visibility</name>
      <type>Main</type>
      <value>hidden</value>
      <webElementGuid>f9d515e1-67be-4ff5-be4e-b62c9b051ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-i8v60ol-2483624&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;huinno-mouse-tracker-g&quot;]/path[@class=&quot;huinno-mouse-tracker&quot;]</value>
      <webElementGuid>ded6591a-887f-4988-9297-a887c356fb3d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
