<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Created with Highcharts 9.3.2_huinno-e_95681c</name>
   <tag></tag>
   <elementGuidId>6866e3bb-d443-4295-97ba-aeb84bd0caee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#highcharts-jivpkqq-131097 > svg.highcharts-root > g.huinno-event-marker-group > g.huinno-event-marker.huinno-EVENT-TYPE-AF > rect.huinno-event-marker-area.huinno-EVENT-TYPE-AF</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>9ea00b6b-25f5-4a9f-a57b-55283df7c9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cca4464c-c4db-4785-a908-57a7e2d31134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a81acbac-8f74-4020-a3a5-1f565c2bd224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1570</value>
      <webElementGuid>87198bf3-4c50-432d-97ff-9332ffe60dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>49613dc6-aab7-4798-af89-a38705d50ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>c9723ffc-3e5d-4f6f-8c35-b366dc60426d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-event-marker-area  huinno-EVENT-TYPE-AF</value>
      <webElementGuid>12a47738-db01-406d-9e62-6ab245933b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(1, 17)</value>
      <webElementGuid>60153c75-59bf-4638-885e-cfcc127b000c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8e5c2989-3ae5-485a-989e-c3838f2a8ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-jivpkqq-131097&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;huinno-event-marker-group&quot;]/g[@class=&quot;huinno-event-marker huinno-EVENT-TYPE-AF&quot;]/rect[@class=&quot;huinno-event-marker-area  huinno-EVENT-TYPE-AF&quot;]</value>
      <webElementGuid>3601566a-e237-4464-bcfc-f0650c66d43e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
