<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Created with Highcharts 9.3.2_huinno-s_7b9607 (1)</name>
   <tag></tag>
   <elementGuidId>c2d7eee1-fd2c-4061-9c7c-b960724135d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#huinno-selectionStrip-1676407830000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//rect[@id = 'huinno-selectionStrip-1676407830000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>3a5f0bfb-2b96-4ea3-8318-4e11c30afc5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>554.0586666666667</value>
      <webElementGuid>e5457d00-31db-4fa0-9a64-9376def3678d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>8fa23a26-0cf3-4bd9-bc5e-0ac2d8820546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>292.8573333333334</value>
      <webElementGuid>be5d3c60-ebae-4e74-aacd-2c6ce8f81938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>5989ee21-d82e-4df3-a114-2ba7faf06760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgba(66,106,255,10%)</value>
      <webElementGuid>0fa4f3fa-6bfb-4bbf-bba6-eda2a01eb080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>huinno-selectionStrip-1676407830000</value>
      <webElementGuid>b11d42eb-4c0f-4ea1-b6a8-81a03216e782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-dashoffset</name>
      <type>Main</type>
      <value>-300</value>
      <webElementGuid>f4cf6866-c33f-41ff-acae-1a7f88f0598f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>ac098785-f960-4202-976c-c02a741b1e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-context-menu-area</value>
      <webElementGuid>9a1b6405-ee3c-4773-b801-cab197115758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;huinno-selectionStrip-1676407830000&quot;)</value>
      <webElementGuid>d0b063b2-ca39-4c87-8334-b406a7fbcf9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//rect[@id = 'huinno-selectionStrip-1676407830000']</value>
      <webElementGuid>d142ff87-db95-407f-9b62-846bea08e8d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
