<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Created with Highcharts 9.3.2_huinno-e_95681c (1)</name>
   <tag></tag>
   <elementGuidId>5d3a4742-4379-4d96-afe7-08e23ceaf475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;highcharts-jivpkqq-131097&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;huinno-event-marker-group&quot;]/g[@class=&quot;huinno-event-marker huinno-EVENT-TYPE-AF&quot;]/rect[@class=&quot;huinno-event-marker-area  huinno-EVENT-TYPE-AF&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#highcharts-jivpkqq-131097 > svg.highcharts-root > g.huinno-event-marker-group > g.huinno-event-marker.huinno-EVENT-TYPE-AF > rect.huinno-event-marker-area.huinno-EVENT-TYPE-AF</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>f17b132d-564d-440b-a4ef-91db40663478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99b1b65d-df66-4897-8b89-2a6ba08a5d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>31f48fb5-1f9c-4d63-b28c-b11ea498dcb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1570</value>
      <webElementGuid>0393ea56-7f17-4184-94de-dc08f54059c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>8f4305bb-07c7-4260-b828-4ea80202e767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>d12ee5b5-ddfa-4c28-ade4-32e97e844b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-event-marker-area  huinno-EVENT-TYPE-AF</value>
      <webElementGuid>066a4012-c86b-4192-b31c-f0c5f95cf83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(1, 17)</value>
      <webElementGuid>37b69cd9-87d2-469d-87b9-bd7babd36f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>90015a19-d0ec-4744-aeaf-18a56246abd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-jivpkqq-131097&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;huinno-event-marker-group&quot;]/g[@class=&quot;huinno-event-marker huinno-EVENT-TYPE-AF&quot;]/rect[@class=&quot;huinno-event-marker-area  huinno-EVENT-TYPE-AF&quot;]</value>
      <webElementGuid>e1ecc63a-d5c6-4589-a93c-199be08ca960</webElementGuid>
   </webElementProperties>
</WebElementEntity>
