<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Created with Highcharts 9.3.2_huinno-e_1b5bf5</name>
   <tag></tag>
   <elementGuidId>304f3075-15d6-4fa4-8c7c-d3907624fe7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#highcharts-jivpkqq-131097 > svg.highcharts-root > g.huinno-event-marker-group > rect.huinno-event-marker-priority.huinno-event-marker-priority-selected.huinno-EVENT-TYPE-AF.huinno-context-menu-area</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>97cb88e8-2e7d-4bb2-bceb-95f543a5a261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bedb7227-49b0-4d85-b6db-720e4f625344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b6cbe02a-7163-4c85-ac06-e7e55763f6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1570</value>
      <webElementGuid>2e66f584-752d-4c46-82df-7f79676b8adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>8fa5c524-6102-4625-a2b6-fe6318c67825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7249a046-f627-4b28-a3e3-2253b8618f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-event-marker-priority huinno-event-marker-priority-selected huinno-EVENT-TYPE-AF huinno-context-menu-area</value>
      <webElementGuid>505d5fa5-62d9-4042-a2d2-245d42b638bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(1, 17)</value>
      <webElementGuid>6ab79643-f60b-467a-b683-2c243f98af1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>4135f413-a9d0-4df8-baab-93f4e2bf8e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-jivpkqq-131097&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;huinno-event-marker-group&quot;]/rect[@class=&quot;huinno-event-marker-priority huinno-event-marker-priority-selected huinno-EVENT-TYPE-AF huinno-context-menu-area&quot;]</value>
      <webElementGuid>959b49e2-539a-4b23-b04c-09f8b8b38803</webElementGuid>
   </webElementProperties>
</WebElementEntity>
