<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Created with Highcharts 9.3.2_huinno-e_1b5bf5_1</name>
   <tag></tag>
   <elementGuidId>7636042e-bb32-43f0-9621-bc87336a639c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>rect.huinno-event-marker-priority.huinno-event-marker-priority-selected.huinno-EVENT-TYPE-AF.huinno-context-menu-area</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>214389af-8304-49bd-affa-1450285de659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>93cd1bfc-9092-4ac1-8228-9be1b67d2eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>199e58b0-109d-4956-9b0b-07345824bd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1139</value>
      <webElementGuid>ac207dc6-9450-4707-bbbd-42b163677389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>47</value>
      <webElementGuid>8ff2f35f-bf41-4554-a273-dae541ccfcb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b6ff6b53-4d18-42e5-9ffd-8e9184c3c258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-event-marker-priority huinno-event-marker-priority-selected huinno-EVENT-TYPE-AF huinno-context-menu-area</value>
      <webElementGuid>96ed3901-5379-4648-a9d3-0ae967a05ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(47.17493333333333, 17)</value>
      <webElementGuid>b7812763-4f6d-42f1-99d7-9748ea16b626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>672df5e0-c0b6-478b-a48f-c9f4c937d395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-fq3j3q5-894556&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;huinno-event-marker-group&quot;]/rect[@class=&quot;huinno-event-marker-priority huinno-event-marker-priority-selected huinno-EVENT-TYPE-AF huinno-context-menu-area&quot;]</value>
      <webElementGuid>ad4d1aee-0f1e-492c-a991-76a4a8ef2404</webElementGuid>
   </webElementProperties>
</WebElementEntity>
