<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Created with Highcharts 9.3.2_huinno-s_7b9607</name>
   <tag></tag>
   <elementGuidId>d11f26e5-f9cf-4697-a92c-434b152a13c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#huinno-selectionStrip-1676407830000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//rect[@id = 'huinno-selectionStrip-1676407830000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>5eaed5b4-2069-4b4e-a8a2-2483e0130883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>554.0586666666667</value>
      <webElementGuid>cdbf89b9-1d69-49fd-9594-06a007ebeff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>093e8b8e-8aaf-4aa2-bb0d-7a674bde11e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>292.8573333333334</value>
      <webElementGuid>c2d4deb1-0071-4574-aa3f-c00157d390a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>ad2ac64a-cf78-476f-8649-b4c32968d7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgba(66,106,255,10%)</value>
      <webElementGuid>a45100a5-ae10-4b82-b854-032386d74d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>huinno-selectionStrip-1676407830000</value>
      <webElementGuid>33026deb-cdd1-44c9-a77f-e19e2b1c00c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-dashoffset</name>
      <type>Main</type>
      <value>-300</value>
      <webElementGuid>99e05b86-ed7f-49d1-82eb-4b33413f0747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>42cb4705-dedf-4b10-a0f8-3490a34b493e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-context-menu-area</value>
      <webElementGuid>607d6060-38e6-4209-9df3-5d57514863a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;huinno-selectionStrip-1676407830000&quot;)</value>
      <webElementGuid>ea114a69-fcab-4864-89dc-a745b89d2db9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//rect[@id = 'huinno-selectionStrip-1676407830000']</value>
      <webElementGuid>55e307f2-4403-4eeb-8e0a-5ee6bee4f11e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
