<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Created with Highcharts 9.3.2_huinno-s_69cb51</name>
   <tag></tag>
   <elementGuidId>a237c26d-95ff-4699-9fbf-1e70daa427f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#huinno-selectionStrip-1675840290000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//rect[@id = 'huinno-selectionStrip-1675840290000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>95a34516-0b84-4581-ad88-0fa0210cfa4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>339.97546666666665</value>
      <webElementGuid>e5ebe34a-1ebc-4024-9cc2-83717ae09ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>f79ec549-d6a4-4124-ab59-c5e5214dd11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>133.99866666666668</value>
      <webElementGuid>32f85d64-967c-446b-b6e6-436f98a0b4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>06b413a8-358b-4e97-83a3-0e7394a8dcc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgba(66,106,255,10%)</value>
      <webElementGuid>138e9450-80fc-4c95-aa6a-c1e901067cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>huinno-selectionStrip-1675840290000</value>
      <webElementGuid>88f54ac7-4007-4a11-b7df-53a51aad076d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-dashoffset</name>
      <type>Main</type>
      <value>-300</value>
      <webElementGuid>1fcbe1d3-f2eb-456e-b6b8-8ba3a1884951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>d118315b-a5f5-4b79-b437-b59584f19510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-context-menu-area</value>
      <webElementGuid>94da64ab-e001-41be-9e3a-07a5d113a11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;huinno-selectionStrip-1675840290000&quot;)</value>
      <webElementGuid>62ea0e8f-cd76-46cf-b3cc-8e0db5f66c6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//rect[@id = 'huinno-selectionStrip-1675840290000']</value>
      <webElementGuid>c49d0de8-7e89-408e-ab7e-4780328cea28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
