<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Created with Highcharts 9.3.2_huinno-e_95681c (2)</name>
   <tag></tag>
   <elementGuidId>e001b2dc-aed9-4ac2-a7f2-052bf9b345a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>rect.huinno-event-marker-area.huinno-EVENT-TYPE-AF</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>6de00a89-7b87-4f5d-90bb-3e937d97aec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>28b0878e-0e47-4e86-814e-dd66db66d95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8d3d01ee-90ab-4bf1-957c-9950b7339d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>228</value>
      <webElementGuid>98fb8b27-c9ff-496f-9eac-5afc072120e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>edaf79d3-f209-4459-be60-6e48657f20b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>e7fa3c42-4377-4081-9834-42e8a84c10a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-event-marker-area  huinno-EVENT-TYPE-AF</value>
      <webElementGuid>aa7b0dab-ad98-4135-aab1-979fb47d8926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(1, 17)</value>
      <webElementGuid>8489b9b2-a44d-4f7d-8d46-d6829158e531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ad842d57-0b8c-4a04-8203-49c6a05950e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-i8v60ol-2483624&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;huinno-event-marker-group&quot;]/g[@class=&quot;huinno-event-marker huinno-EVENT-TYPE-AF&quot;]/rect[@class=&quot;huinno-event-marker-area  huinno-EVENT-TYPE-AF&quot;]</value>
      <webElementGuid>cd6a43cb-bccb-4c59-9a35-4264b718b01d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
