<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Created with Highcharts 9.3.2_huinno-e_1b5bf5 (2)</name>
   <tag></tag>
   <elementGuidId>35f2ce4b-c79d-425e-8de9-052e235ef323</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[local-name()='svg']//*[name()='g']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>581d5fa5-d0cf-4932-ad73-54bcc91611a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9cef52fb-9b8d-4e5c-acdc-fa82b562eb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d4b381cb-acb1-40cc-a1f3-1fac707bc5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1139</value>
      <webElementGuid>44028213-6c8c-45e6-acc9-e77d6e41fb56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>47</value>
      <webElementGuid>ead5cc36-106d-44b4-ac88-c0cedafa3817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>e0ba85ed-20ce-4bff-b2b1-29597d5dcbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-event-marker-priority huinno-event-marker-priority-selected huinno-EVENT-TYPE-AF huinno-context-menu-area</value>
      <webElementGuid>74e7d1e7-ce5c-4f98-9c36-ffed1bcdb9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(47.17493333333333, 17)</value>
      <webElementGuid>3a746724-e5bd-468a-af43-a6898ad4b29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>116a253e-2ba2-4a42-8d25-91784b61519e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[local-name()='svg']//*[name()='g' and @class = &quot;huinno-event-marker huinno-EVENT-TYPE-AF&quot;]</value>
      <webElementGuid>2e1cdf28-36aa-4ff1-a594-2b0e7b9b690f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
