<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_57c53fd8</name>
   <tag></tag>
   <elementGuidId>3fd3c282-2e8b-420c-8b63-2942467c1168</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-hFxENk.dyRgLR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>055edd7e-45b7-494c-9c52-72278629212f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hFxENk dyRgLR</value>
      <webElementGuid>45229433-3dcb-4181-81e1-fb693ddf2768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>57c53fd8</value>
      <webElementGuid>a99719c6-5cc8-48c2-af18-adc0e5200e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-jWUzzU dgZbAM&quot;]/div[@class=&quot;sc-eFegNN cGKrit&quot;]/div[@class=&quot;sc-ePIFMk cEzwjs&quot;]/div[@class=&quot;sc-iNpzLj bkOPlI&quot;]/div[@class=&quot;sc-iyyVIK fFOhXs&quot;]/div[@class=&quot;sc-hFxENk dyRgLR&quot;]</value>
      <webElementGuid>90f5ffd6-c781-4f88-8ec0-a5496812f7ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div</value>
      <webElementGuid>d9078447-cb91-49d8-a852-34291f575835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version 2.2.1'])[1]/following::div[5]</value>
      <webElementGuid>07174ea3-e724-44fa-9e1e-4c006c44d9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='로그아웃'])[1]/following::div[7]</value>
      <webElementGuid>e5e49dbb-64fd-406a-8ea0-3f4ebf72e9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[1]/preceding::div[1]</value>
      <webElementGuid>2aa97cee-555b-40aa-b0b1-bcf539acdb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event Review'])[1]/preceding::div[3]</value>
      <webElementGuid>d9651c9e-87e4-4306-9e09-30f8dd92d2b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='57c53fd8']/parent::*</value>
      <webElementGuid>fdfa38ed-d0ae-4158-8108-b77371acf248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>66cc9f30-a3fb-4c66-8ac1-9decbd790cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '57c53fd8' or . = '57c53fd8')]</value>
      <webElementGuid>cf9a7e82-b63f-41a4-b1a9-104c0181a5a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
