<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1_2</name>
   <tag></tag>
   <elementGuidId>3a4451a2-108c-478d-9a9b-b591133d21ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[2]/div/div/div/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-cRKLkh.heoShc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76c592ef-0a92-4144-ac51-231c53470717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-cRKLkh heoShc</value>
      <webElementGuid>46b73f50-3aba-4dae-b849-9fce5c209fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>:</value>
      <webElementGuid>39a7394b-08ed-4eae-9518-3029402df278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-jWUzzU dgZbAM&quot;]/div[@class=&quot;sc-eFegNN cGKrit&quot;]/div[@class=&quot;sc-eBHJIF jnAICa&quot;]/div[@class=&quot;sc-ewSTlh jlayFw&quot;]/div[@class=&quot;sc-fDMmqs hWPHwC&quot;]/div[@class=&quot;sc-lVTEl elpYdT&quot;]/div[@class=&quot;sc-iboAsT bJXNhr&quot;]/div[@class=&quot;sc-cAhXWc kyALKw&quot;]/div[@class=&quot;sc-gqtqkP izLUeC&quot;]/div[@class=&quot;sc-fIITEw ciKSLs&quot;]/div[@class=&quot;sc-cRKLkh heoShc&quot;]</value>
      <webElementGuid>3bc8119e-b23f-492e-b7fa-fa9002e25b3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>29f81d5d-cd6a-43f4-ba0d-83f886db336c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='검토 완료'])[1]/following::div[12]</value>
      <webElementGuid>c6856b7f-6a2f-4b28-9ee8-7af97386adb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='리포트 생성'])[1]/following::div[14]</value>
      <webElementGuid>5ec9e6c0-c09a-4f93-97ae-8d79ea2981cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recording Time: 2022-11-17, 14:14 ~ 2022-12-01, 13:16'])[1]/preceding::div[2]</value>
      <webElementGuid>b9e922d3-2510-418d-9c8a-91f1dd967b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>8685ed08-6623-4166-8fa7-3c2805978cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ':' or . = ':')]</value>
      <webElementGuid>f38c0851-4789-4d88-997b-7c04cbd9c55e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
