<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_V_highcharts-button-box_1</name>
   <tag></tag>
   <elementGuidId>abd9cb13-92ae-4f3c-b5f2-c4763624eff9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>g.beats-event-button-1638.highcharts-button-hover > rect.highcharts-button-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>534e5455-db9e-4a32-9dc0-03fe92d76c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#E6EAEC</value>
      <webElementGuid>924324eb-927a-46e3-897c-32c69d64940b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-button-box</value>
      <webElementGuid>f4a943ef-28c0-47e0-89f2-22e6caf559f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0.5</value>
      <webElementGuid>92c7f392-a287-4e09-8dae-0620e95247b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0.5</value>
      <webElementGuid>bf8ce245-4d0d-45ba-8e56-8bce28674e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>edcc55ba-8b0a-4e7b-8470-3f3e96c43989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>28de1d38-c0b9-47e5-8d6f-2df1068c92ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rx</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4655aea3-41ba-49c0-a08c-7f8f8571b950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ry</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a708ebf6-f06b-4552-941a-5de8f9d97301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#c7ced2</value>
      <webElementGuid>fee6809e-af98-4b4f-ae1b-4a9e81dc349c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a6673c52-d2e5-4fd6-ba4a-5d89947398f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-c5xbxhh-397586&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;beats-event-button-1638 highcharts-button-hover&quot;]/rect[@class=&quot;highcharts-button-box&quot;]</value>
      <webElementGuid>a8ca70ff-9663-404b-8c4a-8b0328c2a383</webElementGuid>
   </webElementProperties>
</WebElementEntity>
