<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Created with Highcharts 9.3.2_huinno-e_95681c</name>
   <tag></tag>
   <elementGuidId>b2060d48-d32a-40ee-8fdc-94abf2c25a8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#highcharts-c5xbxhh-176383 > svg.highcharts-root > g.huinno-event-marker-group > g.huinno-event-marker.huinno-EVENT-TYPE-AF > rect.huinno-event-marker-area.huinno-EVENT-TYPE-AF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>db0eb48c-8df7-4c63-b3d6-ba14710ea0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9f50b8d9-bfbf-4c39-a1c9-4da9580516d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c44f3e16-dcb0-4191-ac2d-15601692d819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>684</value>
      <webElementGuid>00fdf910-4f84-4cd8-ab16-44fa50679319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>4e3b9420-d5a1-40f5-a745-6d5382c515da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>d938d41e-1063-4470-8e94-26dae51094e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-event-marker-area  huinno-EVENT-TYPE-AF</value>
      <webElementGuid>58fb1d38-d7c5-4d0c-8d6d-c5241c709f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(1, 17)</value>
      <webElementGuid>bdb11ee4-595a-4f55-932f-3f8a5e293db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3de72eca-33ed-4bb4-8418-995b383e323d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-c5xbxhh-176383&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;huinno-event-marker-group&quot;]/g[@class=&quot;huinno-event-marker huinno-EVENT-TYPE-AF&quot;]/rect[@class=&quot;huinno-event-marker-area  huinno-EVENT-TYPE-AF&quot;]</value>
      <webElementGuid>727e9eb6-17b6-4adb-b280-4765c67f7e74</webElementGuid>
   </webElementProperties>
</WebElementEntity>
