<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Created with Highcharts 9.3.2_huinno-s_040835</name>
   <tag></tag>
   <elementGuidId>9f5699be-44f0-4126-bc2b-fc1545acffda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//rect[@id = 'huinno-selectionStrip-1668757800000']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#huinno-selectionStrip-1668757800000</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>d40af1e8-3f5d-4da4-91f2-78e88255d4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>55.9936</value>
      <webElementGuid>c5cde97a-8730-48be-be8a-2bf950136650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>ff7b40c1-d63a-4530-accd-c982a4757634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>121.02240000000002</value>
      <webElementGuid>8ee76ed7-7024-4a62-9ae6-4ef00b395d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>37d98987-f193-4f21-ac36-53ab2b3e78d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgba(66,106,255,10%)</value>
      <webElementGuid>bf2d88df-5e8d-4f40-9c87-09d9b15903e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>huinno-selectionStrip-1668757800000</value>
      <webElementGuid>72097325-913a-41d8-a779-85771073ba71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-dashoffset</name>
      <type>Main</type>
      <value>-300</value>
      <webElementGuid>1bd2457c-3e9e-4776-9f21-02373b1e90cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>515b472f-f830-4112-bf9d-790b06392fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-context-menu-area</value>
      <webElementGuid>575c89f2-2f4c-4627-9d2d-76716c31e56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;huinno-selectionStrip-1668757800000&quot;)</value>
      <webElementGuid>0cef9511-3c84-41b8-90ca-67936018db57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//rect[@id = 'huinno-selectionStrip-1668757800000']</value>
      <webElementGuid>22a49043-7379-478e-94a8-b014e1eaadd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
