<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>u_Q</name>
   <tag></tag>
   <elementGuidId>80d5f5c5-7209-4fd6-befa-cf024461dc97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//u[@id='N']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#N > #N</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>u</value>
      <webElementGuid>2ec4255f-f5cb-401b-abd6-d4ce5e2e0f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>e103eec4-892b-41ff-a178-cbe7cf62982a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2efcd717-23b3-4152-aad5-a243e27dfb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Q </value>
      <webElementGuid>63e40cdd-aabe-4238-a2a2-d1c1f0e217d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Normal&quot;)/div[@class=&quot;sc-hiwPVj frZFbt&quot;]/div[@id=&quot;N&quot;]/u[@id=&quot;N&quot;]</value>
      <webElementGuid>833bdfb0-0d28-4438-a3dd-d0cc5a9ec4a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//u[@id='N']</value>
      <webElementGuid>0c20de16-eebd-4dc7-aebe-f7b14b00b362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='N']/u</value>
      <webElementGuid>86c75f82-d0fe-4140-a33e-5440ce031aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created with Highcharts 9.3.2'])[31]/following::u[1]</value>
      <webElementGuid>1215aa1e-e001-45ec-b18e-97dba6bdc645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//u</value>
      <webElementGuid>9610a2e0-8b7d-45fa-a01a-81df60f17467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//u[@id = 'N' and (text() = ' Q ' or . = ' Q ')]</value>
      <webElementGuid>306678e2-845a-4c1b-b103-3fa174b4b5f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
