<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>32ee4400-2e3a-4129-b76e-0916948018ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-pVTFL.cVdCiw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd121dd6-ecff-4533-8e0a-b94abda4ebc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-pVTFL cVdCiw</value>
      <webElementGuid>bdc7d2b8-6a1b-4560-a14c-a8c723f5511c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>확인</value>
      <webElementGuid>54e0f8e2-7aec-4f2f-bcbe-d072d5fe9c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-bdvvtL rRhHO&quot;]/div[@class=&quot;sc-gsDKAQ lZxQq&quot;]/div[@class=&quot;sc-jRQBWg fiaAfi&quot;]/button[@class=&quot;sc-pVTFL cVdCiw&quot;]</value>
      <webElementGuid>1ac25e1a-dac0-4a45-9ff6-fac809cf16c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/button[2]</value>
      <webElementGuid>efaf5678-4321-438d-ae80-f6d6e00186eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[1]/following::button[1]</value>
      <webElementGuid>d8abaf4a-9540-433b-b6f3-7a278a7a0841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Min'])[1]/following::button[2]</value>
      <webElementGuid>7e937ed1-a40a-430f-bb98-c7adb9f27202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='확인']/parent::*</value>
      <webElementGuid>cebd4664-fc52-4e43-96a0-8caf34e9dd6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>dfaaf724-8a21-4bfb-83bf-b03401e8eb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '확인' or . = '확인')]</value>
      <webElementGuid>c32c9b70-aa8d-4fdf-acea-31877ae8443c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
