<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Set Min</name>
   <tag></tag>
   <elementGuidId>0cf7e1ec-f19d-45ac-8ec1-0c206bbf947c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[2]/div/div[2]/div/div[5]/div/div[4]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>86f69ed7-918c-423a-b0b3-99e7a7293033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hiwPVj frZFbt</value>
      <webElementGuid>0b1d91b6-20a9-4e9c-976f-44daa6969eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Set Min</value>
      <webElementGuid>7a96d3a3-ce48-49c8-9f0d-e16ee75be676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-jWUzzU dgZbAM&quot;]/div[@class=&quot;sc-eFegNN cGKrit&quot;]/div[@class=&quot;sc-eBHJIF jnAICa&quot;]/div[@class=&quot;sc-ewSTlh jlayFw&quot;]/div[@class=&quot;sc-emDsmM fZVbx&quot;]/div[@class=&quot;sc-ekrjqK eeWkHX&quot;]/div[@class=&quot;sc-jftFmt daeLlX&quot;]/div[@class=&quot;sc-fGoOlv dfnGou&quot;]/div[@class=&quot;sc-gJbFto jnCPVG&quot;]/div[@class=&quot;sc-eJRTFu llHmiU&quot;]/div[@class=&quot;sc-jeraig cGdVOZ&quot;]/div[@class=&quot;sc-hiwPVj frZFbt&quot;]</value>
      <webElementGuid>46bc9e01-fc41-4d64-8cbb-045a02b5cced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/div[2]/div/div[5]/div/div[4]/div/div</value>
      <webElementGuid>1a758f0a-5fc0-4d50-88d7-1eee6ee286bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Max'])[1]/following::div[3]</value>
      <webElementGuid>309e028e-587e-4692-9cf8-932ebaa54379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Higher HR'])[1]/following::div[7]</value>
      <webElementGuid>e2321bae-a3ae-4ded-bea6-88332812e7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Set Min']/parent::*</value>
      <webElementGuid>db249e91-59d4-40f9-aae0-a99151b40517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[4]/div/div</value>
      <webElementGuid>4dc9315d-dceb-4357-b800-e1958908bb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Set Min' or . = 'Set Min')]</value>
      <webElementGuid>85b9b5dc-7674-438e-8dc1-083939394415</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
