<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect</name>
   <tag></tag>
   <elementGuidId>72b2da8f-b6ba-458d-aaa2-383eb0c1e7ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;selectSvg&quot;)/rect[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = '250 bpm, 4 beats </value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectSvg > rect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>ce6ee5d0-cd31-4bf0-a28e-91924e9baf3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ab856824-2581-420d-9bdc-698288a14d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>af832485-1933-4cd1-a517-86a037b2640a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>51448747-0a90-489d-bb81-824699cd6c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>7eb71d7f-ef40-454c-9a47-85008c32413b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>91124d5d-d77e-478d-800e-1dc6cca89d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#426AFF</value>
      <webElementGuid>f6eec675-e5ba-4bee-b315-df7ce47e6da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8f789762-953c-4cb5-bd2f-971f83859c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectSvg&quot;)/rect[1]</value>
      <webElementGuid>e39dc2f3-64e9-456d-a852-c01c5a46c378</webElementGuid>
   </webElementProperties>
</WebElementEntity>
