<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>de585e1f-bbdd-4e1b-950b-3a8063e9b58b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='검토 완료'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-nVkyK.dAcCno > svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>bf1c4df6-f27e-4c1c-92ad-f099d34829bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>6a8b17bf-70ef-48c7-9368-b3bcbdd92c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>cd582b0c-bb36-42a4-9a5a-b19be5089846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 14 6</value>
      <webElementGuid>82a50d49-8b26-47c2-982a-660a683e2155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2d6050ac-1250-4ae2-9830-dfed2fcb8585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>ec561605-9922-49c7-80fc-44e9787d9542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-jWUzzU dgZbAM&quot;]/div[@class=&quot;sc-eFegNN cGKrit&quot;]/div[@class=&quot;sc-eBHJIF jnAICa&quot;]/div[@class=&quot;sc-ewSTlh jlayFw&quot;]/div[@class=&quot;sc-emDsmM fZVbx&quot;]/div[@class=&quot;sc-bvFjSx gnjJaT&quot;]/div[@class=&quot;sc-bttaWv dWnHuN&quot;]/div[@class=&quot;sc-fTQvRK jIKLRW&quot;]/div[@class=&quot;sc-bUhFKy hVcqeF&quot;]/div[@class=&quot;sc-jeraig RzUpv&quot;]/div[@class=&quot;sc-nVkyK dAcCno&quot;]/svg[1]</value>
      <webElementGuid>17255ad3-fb3f-4b3f-b267-c594acd3ebf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='검토 완료'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>4733a639-e75c-422d-85ad-18ee670e0ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='리포트 생성'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>d3359960-5894-4156-a69e-1d22b692fc10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revert'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>c42695af-438d-481a-b6b2-fc105fb9c17b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recording Time: 2023-02-22, 14:25 ~ 2023-03-01, 14:25'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>e8fa8f34-17d0-49c2-a657-28bd53a029d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
