<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_</name>
   <tag></tag>
   <elementGuidId>fef31fec-fe6e-46df-9bad-d15e0d6ee8fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='+']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>g.highcharts-no-tooltip.highcharts-button.highcharts-button-hover > text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f09b7c07-9c3d-4563-ab28-9987b76c2ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>7451ecb6-c7b5-4e55-83be-561ee124d94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>be6bfd4a-645f-4057-aa82-ac511de21c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>16.5</value>
      <webElementGuid>a451665e-5657-4e32-a7f5-96f334064a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>6686fd33-0577-4c3b-9cc5-ed032f330a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-falug0l-50071&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;huinno-mouse-tracker&quot;]/g[@class=&quot;highcharts-no-tooltip highcharts-button highcharts-button-hover&quot;]/text[1]</value>
      <webElementGuid>1cd8b543-796d-4943-8c99-ec660ef2ab73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+']/parent::*</value>
      <webElementGuid>b8e9e86c-f033-4f3d-b29d-6adc680f154d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = '+' or . = '+')]</value>
      <webElementGuid>f2b59831-84a2-4f00-8fc6-3e9ac64199c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
