<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_141400</name>
   <tag></tag>
   <elementGuidId>97eaf3ec-5808-4f76-960c-029a4cd34aea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b73a4021-e614-4065-ab0c-7730d85b2732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fvpsdx tIIFn</value>
      <webElementGuid>6455676c-89dd-4871-ad43-2c7b0b7812cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>14:14:00</value>
      <webElementGuid>0221d8fc-8549-4d78-9d99-ac942b1d7149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-jWUzzU dgZbAM&quot;]/div[@class=&quot;sc-eFegNN cGKrit&quot;]/div[@class=&quot;sc-eBHJIF jnAICa&quot;]/div[@class=&quot;sc-ewSTlh jlayFw&quot;]/div[@class=&quot;sc-fDMmqs hWPHwC&quot;]/div[@class=&quot;sc-lVTEl elpYdT&quot;]/div[@class=&quot;sc-eSJyHI fbCugD&quot;]/div[@class=&quot;sc-jnrVZQ lmpOfX&quot;]/div[1]/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;sc-kjOQFR hoMJYh&quot;]/div[@class=&quot;sc-bXdNzS iHzBlg&quot;]/div[@class=&quot;sc-eySxxw hnEDOu&quot;]/div[@class=&quot;sc-fvpsdx tIIFn&quot;]</value>
      <webElementGuid>407c22dc-3f6c-4729-8150-e2f1ca6bae2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>26000184-42f6-411d-8b44-c3666643ca09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created with Highcharts 9.3.2'])[2]/following::div[12]</value>
      <webElementGuid>a7806b4c-05c0-4e37-9f42-68681c04f473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bpm'])[1]/following::div[15]</value>
      <webElementGuid>661c64fc-b975-4b1f-9195-aabdd7ccc933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created with Highcharts 9.3.2'])[3]/preceding::div[1]</value>
      <webElementGuid>ebe7738c-daf0-47e0-92f5-bb39e791de02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created with Highcharts 9.3.2'])[4]/preceding::div[8]</value>
      <webElementGuid>1e0e796b-cd19-4223-ad2b-2cc9f01ac9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='14:14:00']/parent::*</value>
      <webElementGuid>ff015905-2445-4204-b850-39e657c50ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>0d69147b-92a1-43e2-9bc8-670e6652b9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '14:14:00' or . = '14:14:00')]</value>
      <webElementGuid>a1c75989-5f5d-4b4b-bb4c-1473af9d5f35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
