<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_Created with Highcharts 9.3.2_huinno-m_7ff2e6</name>
   <tag></tag>
   <elementGuidId>e8cd2c33-f84f-455a-a145-88b896d75d72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>path.huinno-mouse-tracker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>f1c9d5f9-0643-41e4-94f5-c1ecbd915f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>8a41f68f-a186-4fc6-977c-b2d35529a189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-mouse-tracker</value>
      <webElementGuid>60089676-2d9e-41d5-9975-723e7bb5b789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M0 17 V44</value>
      <webElementGuid>6211e310-cbb5-45b8-8737-8fa993e6e01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>rgb(66, 106, 255)</value>
      <webElementGuid>f2005aad-9bb6-4398-ab1e-2ae332343fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7c173622-2e30-422e-83e4-ac74d32189d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-dasharray</name>
      <type>Main</type>
      <value>2,2</value>
      <webElementGuid>e694dfd5-908a-4c11-b780-6739af580dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>visibility</name>
      <type>Main</type>
      <value>hidden</value>
      <webElementGuid>6f71e3a3-5bf2-4802-a5e1-7af41634c885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-fe5lu73-3&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;huinno-mouse-tracker-g&quot;]/path[@class=&quot;huinno-mouse-tracker&quot;]</value>
      <webElementGuid>2a00554d-7cf3-4b38-9245-3f28f8abe18c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
