<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Created with Highcharts 9.3.2_huinno-e_9fb137</name>
   <tag></tag>
   <elementGuidId>efa5f753-98e3-4116-94fb-8d87d9c17013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>rect.huinno-event-marker-area.huinno-EVENT-TYPE-RUN-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>dab2256c-c64a-423f-85c0-532238f7fe68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>24970651-301c-4a56-a73b-5ed44c8cf021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6b8875ab-2127-40cb-bd32-3c201fc5348e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>331</value>
      <webElementGuid>9eda06cf-ecff-458f-837d-9d349e0a1ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>ca61ee41-8e76-4522-8eb5-82d023248b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>027d04f1-9f1d-4b25-adb9-90f2248394ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-event-marker-area  huinno-EVENT-TYPE-RUN-1</value>
      <webElementGuid>cb14ebe8-7a8f-4dc9-99bf-8294d07eb8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(213.6784, 17)</value>
      <webElementGuid>d4b2f236-7ff9-43a1-9902-28ecde120ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>abd35004-92fc-405f-a201-0e0f46311a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-fe5lu73-3&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;huinno-event-marker-group&quot;]/g[@class=&quot;huinno-event-marker huinno-EVENT-TYPE-RUN-1&quot;]/rect[@class=&quot;huinno-event-marker-area  huinno-EVENT-TYPE-RUN-1&quot;]</value>
      <webElementGuid>775801cb-0075-4ee0-8544-0729a1ba056b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
