<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Created with Highcharts 9.3.2_huinno-s_5b89a8</name>
   <tag></tag>
   <elementGuidId>1848823d-470f-4851-8e14-4f665e414c09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#huinno-selectionStrip-1676388900000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//rect[@id = 'huinno-selectionStrip-1676388900000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>48cf3fdd-eb64-482f-8ae2-92a0ea93b5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>319.9549333333333</value>
      <webElementGuid>cf1cf826-fa88-4bce-93f0-c0efd2fd9319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>9ab76cbc-7f09-4bef-a699-2a743513cde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>323.06639999999993</value>
      <webElementGuid>6f49cc78-81c4-4608-a7db-2779588ebd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>47</value>
      <webElementGuid>b58cba4c-075c-41d8-842e-bbe908090e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgba(66,106,255,10%)</value>
      <webElementGuid>ee71251e-cf60-4e16-9a01-cabc1eb84b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>huinno-selectionStrip-1676388900000</value>
      <webElementGuid>a9bc1c5e-c84f-43e4-b56e-0583f228a53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-dashoffset</name>
      <type>Main</type>
      <value>-300</value>
      <webElementGuid>c4a2ced0-8a67-44dc-9110-2ac9de488d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>6f642c71-ff05-441f-9317-8c9e1cb63548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>huinno-context-menu-area</value>
      <webElementGuid>b487d252-a87c-44b3-92ba-8f10b750d6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;huinno-selectionStrip-1676388900000&quot;)</value>
      <webElementGuid>d1f79e20-4111-4875-9787-f61f74d6f62c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//rect[@id = 'huinno-selectionStrip-1676388900000']</value>
      <webElementGuid>eeb1736e-b16b-4bf1-b26b-eb7315bcad47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
